# GoReleaser configuration for tunatap
# Documentation: https://goreleaser.com
#
# Versioning: CalVer (YYYY.MM.BUILD)
#   - 2026.01.1 = First release of January 2026
#   - 2026.01.2 = Second release of January 2026
#   - 2026.02.1 = First release of February 2026

version: 2

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: tunatap
    main: .
    binary: tunatap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  # For snapshot builds, use current date + dev suffix
  version_template: "{{ .Tag }}-dev+{{.ShortCommit}}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Security
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 2
    - title: Other
      order: 999

release:
  github:
    owner: scotttball
    name: tunatap
  draft: false
  prerelease: auto
  # CalVer doesn't use 'v' prefix
  name_template: "{{.ProjectName}} {{.Version}}"
  header: |
    ## Tunatap {{.Version}}

    SSH tunnel manager for OCI Bastion services.

    ### What's New
    See the changelog below for details on what's changed in this release.

    ### Installation

    **Go Install (requires Go 1.21+):**
    ```bash
    go install github.com/scotttball/tunatap@latest
    ```

    **Direct Download:**
    Download the appropriate archive for your platform from the assets below, extract, and add to your PATH.
  footer: |
    ---
    **Full Changelog**: https://github.com/scotttball/tunatap/compare/{{ .PreviousTag }}...{{ .Tag }}

    **Verify Checksums:**
    ```bash
    sha256sum -c checksums.txt
    ```
